import{i as c,S as u}from"./assets/vendor-0fc460d7.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const r of t.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&n(r)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();function d(o){const s="43995024-c8f5c7e28b3078307d7d8500b",a="https://pixabay.com",n="/api/",e=new URLSearchParams({key:s,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}),t=`${a}${n}?${e}`;return fetch(t).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()}).then(r=>r.hits).catch(r=>{c.error({title:"Error",message:r})})}function p({webformatURL:o,largeImageURL:s,tags:a,likes:n,views:e,comments:t,downloads:r}){return`
<li class="gallery-item">
<a class="gallery-link" href="${s}">
<img src="${o}" alt='${a}'class="gallery-image"/>
</a>
<div class="caption-wrapper">
<p><span>Likes: </span>${n}</p>
<p><span>Views: </span>${e}</p>
<p><span>Comments: </span>${t}</p>
<p><span>Downloads: </span>${r}</p>
</div>

</li>`}function m(o){return o.map(p).join("")}const i={formEl:document.querySelector("#searchForm"),inputEl:document.querySelector("#searchInput"),submitBtn:document.querySelector("#submitButton"),searchRes:document.querySelector("#searchResults"),loaderEl:document.querySelector(".loader"),backdropEl:document.querySelector(".loader-backdrop")},f=new u("#searchResults a",{overlay:!0,captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250,captionClass:"caption",close:!0,showCounter:!0,enableKeyboard:!0,docClose:!0,clasName:"gallery-item-modal"});document.addEventListener("DOMContentLoaded",l);function l(){i.loaderEl.classList.add("visually-hidden"),i.backdropEl.classList.add("visually-hidden")}function h(){i.loaderEl.classList.remove("visually-hidden"),i.backdropEl.classList.remove("visually-hidden")}i.formEl.addEventListener("submit",y);function y(o){if(o.preventDefault(),i.searchRes.innerHTML="",h(),!i.inputEl.value){c.error({title:"Error",message:"Please enter search parameters"}),l();return}const s=o.target.elements.query.value.trim().toLowerCase();d(s).then(a=>{a.length===0&&c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});const n=m(a);i.searchRes.innerHTML=n,f.refresh(),l()}).catch(a=>{c.error({title:"Error",message:"Illegal operation"}),l()}).finally(()=>{l()}),o.target.reset()}
//# sourceMappingURL=commonHelpers.js.map
