import{i as l,S as u}from"./assets/vendor-0fc460d7.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const r of t.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&n(r)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();function d(o){const s="43995024-c8f5c7e28b3078307d7d8500b",a="https://pixabay.com",n="/api/",e=new URLSearchParams({key:s,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}),t=`${a}${n}?${e}`;return fetch(t).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()}).then(r=>r.hits).catch(r=>{l.error({title:"Error",message:r})})}function m({webformatURL:o,largeImageURL:s,tags:a,likes:n,views:e,comments:t,downloads:r}){return`
<li>
<a class="gallery-link" href="${s}">
<img src="${o}" alt='${a}'/>
<p class="coin-title">Likes: ${n}</p>
<p class="coin-price">Views: ${e}</p>
<p class="coin-title">Comments: ${t}</p>
<p class="coin-price"> Downloads: ${r}</p></a>
</li>`}function p(o){return o.map(m).join("")}const i={formEl:document.querySelector("#searchForm"),inputEl:document.querySelector("#searchInput"),submitBtn:document.querySelector("#submitButton"),searchRes:document.querySelector("#searchResults"),loaderEl:document.querySelector(".loader"),backdropEl:document.querySelector(".loader-backdrop")},f=new u("#searchResults a",{overlay:!0,captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250,captionClass:"caption",close:!0,showCounter:!0,enableKeyboard:!0,docClose:!0,clasName:"gallery-item-modal"});document.addEventListener("DOMContentLoaded",c);function c(){i.loaderEl.classList.add("visually-hidden"),i.backdropEl.classList.add("visually-hidden")}function h(){i.loaderEl.classList.remove("visually-hidden"),i.backdropEl.classList.remove("visually-hidden")}i.formEl.addEventListener("submit",y);function y(o){if(o.preventDefault(),i.searchRes.innerHTML="",h(),!i.inputEl.value){l.error({title:"Error",message:"Please enter search parameters"}),c();return}const s=o.target.elements.query.value.trim().toLowerCase();d(s).then(a=>{a.length===0&&l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});const n=p(a);i.searchRes.innerHTML=n,f.refresh(),c()}).catch(a=>{l.error({title:"Error",message:"Illegal operation"}),c()}).finally(()=>{c()}),o.target.reset()}
//# sourceMappingURL=commonHelpers.js.map
